# Generated by Django 3.2.6 on 2021-08-13 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.BigIntegerField(default=0)),
                ('group_order', models.IntegerField(default=0)),
                ('group_indent', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('hits', models.BigIntegerField(default=0)),
                ('tags', models.CharField(max_length=400, null=True)),
                ('password', models.CharField(max_length=300)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('secret_is', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(max_length=255)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
            options={
                'db_table': 'files',
            },
        ),
    ]
