# Generated by Django 3.2.6 on 2021-08-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('title', models.CharField(max_length=300)),
                ('hits', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('secret_is', models.BooleanField(default=False)),
                ('tag', models.CharField(max_length=300, null=True)),
                ('admin_is_answer', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
