# Generated by Django 3.2.6 on 2021-08-06 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('head', models.CharField(max_length=300)),
                ('hits', models.IntegerField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('secret_is', models.BooleanField(default=False)),
                ('tag', models.CharField(max_length=300, null=True)),
                ('admin_is_answer', models.BooleanField(default=False)),
                ('admin_answer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admins.admin')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
